### PR TITLE
APPSRE-2693: Adds feature to enforce unique fields

### PR DESCRIPTION
**Pull request by jmelis**
This PR introduces a new feature that enforces that a given field must be unique across all the datafiles of the same schema.

The GraphQL schema defined in the bundle now allows users to mark fields with the `isUnique: true` attribute. This will fail the validation the field is repeated.

For example, with this schema:

```yaml
datafile: /app-sre/saas-file-1.yml
name: SaasFile_v1
fields:
  - name: name
    type: string
    isRequired: true
    isSearchable: true
    isUnique: true
  - ...
```

### CODE REVIEW

**Comment by jmelis** [comment]
@2uasimojo this is also related to https://github.com/app-sre/qontract-server/pull/93. Since now we are free to extend the GraphQL schema, we can do interesting things like this one.

**Comment by 2uasimojo** [comment]
Ah, nice.

**Comment by 2uasimojo** [comment]
To be clear: if I mark a field as both unique and searchable, and then search on it, the result I get is _still_ a list; just guaranteed to have (zero or) one element. Right?

**Comment by 2uasimojo** [comment]
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/11457 to make SaasFile_v1.name unique.

**Review by maorfr — APPROVED** [review]
LGTM

**Pull request merged**
